joint_trajectory_controller:
  ros__parameters:
    joints: 
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6

    command_interfaces:
      - position
    state_interfaces:
      - position
    state_publish_rate: 1000.0
    action_monitor_rate: 1000.0
