controller_joint_names: [joint1', 'joint2', 'joint3', 'joint4', 'joint5', 'joint6']

kr_50_r2500:
  sample_period: 1.0e-3

  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  robust_inverse_dynamics:
    type: robot_control/RobustInverseDynamicsControl
    base_frame: world
    tool_frame: link6
    setpoint_topic_name: "/kr_50_r2500/joint_target"
    natural_frequency: 100   # natural frequency of the closed loop
    damping: 1              # relative damping of the closed loop
    robustness_gain: 0.01   # robustness gain

  gripper_controller:
    type: robot_control/MimicEffortController
    joint_names:
    - right_finger_joint
    - left_finger_joint

    leading_joint: "right_finger_joint"
    setpoint_topic_name: "/gripper/joint_target"
    multiplier: [1.0, 1.0]
    offset: [0.0, 0.0]
