<?xml version="1.0"?>
<robot  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="central_floor_size_x" value="0.75" />
  <xacro:property name="central_floor_size_y" value="0.75" />
  <xacro:property name="central_floor_size_z" value="0.10" />

  <xacro:property name="lateral_floor_size_x" value="6" />
  <xacro:property name="lateral_floor_size_y" value="2.625" />
  <xacro:property name="lateral_floor_size_z" value="0.20" />

  <xacro:property name="back_wall_size_x" value="6" />
  <xacro:property name="back_wall_size_y" value="0.2" />
  <xacro:property name="back_wall_size_z" value="3" />

  <link name="central_floor">
    <visual>
      <origin xyz="0 0 ${-0.5*central_floor_size_z}" rpy="0 0 0" />
      <geometry>
        <box size="${central_floor_size_x} ${central_floor_size_y} ${central_floor_size_z}" />
      </geometry>
      <material name="White">
        <color rgba="1 1 1 0.1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${-0.5*central_floor_size_z}" rpy="0 0 0" />
      <geometry>
        <box size="${central_floor_size_x} ${central_floor_size_y} ${central_floor_size_z}" />
      </geometry>
      <material name="White">
        <color rgba="1 1 1 0.1"/>
      </material>
    </collision>
  </link>

  <link name="right_floor">
    <visual>
      <origin xyz="0 0.1875 0" rpy="0 0 0" />
      <geometry>
        <box size="${lateral_floor_size_x} ${lateral_floor_size_y} ${lateral_floor_size_z}" />
      </geometry>
      <material name="White">
        <color rgba="1 1 1 0.1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0.1875 0" rpy="0 0 0" />
      <geometry>
        <box size="${lateral_floor_size_x} ${lateral_floor_size_y} ${lateral_floor_size_z}" />
      </geometry>
      <material name="White">
        <color rgba="1 1 1 0.1"/>
      </material>
    </collision>
  </link>

  <link name="left_floor">
    <visual>
      <origin xyz="0 -0.1875 0" rpy="0 0 0" />
      <geometry>
        <box size="${lateral_floor_size_x} ${lateral_floor_size_y} ${lateral_floor_size_z}" />
      </geometry>
      <material name="White">
        <color rgba="1 1 1 0.1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 -0.1875 0" rpy="0 0 0" />
      <geometry>
        <box size="${lateral_floor_size_x} ${lateral_floor_size_y} ${lateral_floor_size_z}" />
      </geometry>
      <material name="White">
        <color rgba="1 1 1 0.1"/>
      </material>
    </collision>
  </link>

  <link name="front_floor">
    <visual>
      <origin xyz="0 -0.1875 0" rpy="0 0 0" />
      <geometry>
        <box size="${lateral_floor_size_x} ${lateral_floor_size_y} ${lateral_floor_size_z}" />
      </geometry>
      <material name="White">
        <color rgba="1 1 1 0.1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 -0.1875 0" rpy="0 0 0" />
      <geometry>
        <box size="${lateral_floor_size_x} ${lateral_floor_size_y} ${lateral_floor_size_z}" />
      </geometry>
      <material name="White">
        <color rgba="1 1 1 0.1"/>
      </material>
    </collision>
  </link>

  <link name="back_floor">
    <visual>
      <origin xyz="0 -0.1875 0" rpy="0 0 0" />
      <geometry>
        <box size="${lateral_floor_size_x} ${lateral_floor_size_y} ${lateral_floor_size_z}" />
      </geometry>
      <material name="White">
        <color rgba="1 1 1 0.1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 -0.1875 0" rpy="0 0 0" />
      <geometry>
        <box size="${lateral_floor_size_x} ${lateral_floor_size_y} ${lateral_floor_size_z}" />
      </geometry>
      <material name="White">
        <color rgba="1 1 1 0.1"/>
      </material>
    </collision>
  </link>

  <link name="back_wall">
    <visual>
      <origin xyz="0 -0.1 1.5" rpy="0 0 0" />
      <geometry>
        <box size="${back_wall_size_x} ${back_wall_size_y} ${back_wall_size_z}" />
      </geometry>
      <material name="White">
        <color rgba="1 1 1 0.1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 -0.1 1.5" rpy="0 0 0" />
      <geometry>
        <box size="${back_wall_size_x} ${back_wall_size_y} ${back_wall_size_z}" />
      </geometry>
      <material name="White">
        <color rgba="1 1 1 0.1"/>
      </material>
    </collision>
  </link>

  <joint name="central_floor_to_right" type="fixed">
      <parent link="central_floor"/>
      <child link="right_floor"/>
      <origin
        xyz="0 1.5 0"
        rpy="0 0 0"/>
  </joint>

  <joint name="central_floor_to_left" type="fixed">
      <parent link="central_floor"/>
      <child link="left_floor"/>
      <origin
        xyz="0 -1.5 0"
        rpy="0 0 0"/>
  </joint>

  <joint name="central_floor_to_front" type="fixed">
      <parent link="central_floor"/>
      <child link="front_floor"/>
      <origin
        xyz="1.5 0 0"
        rpy="0 0 1.57079632679"/>
  </joint>

  <joint name="central_floor_to_back_floor" type="fixed">
      <parent link="central_floor"/>
      <child link="back_floor"/>
      <origin
        xyz="-1.5 0 0"
        rpy="0 0 -1.57079632679"/>
  </joint>

  <joint name="central_floor_to_back_wall" type="fixed">
      <parent link="central_floor"/>
      <child link="back_wall"/>
      <origin
        xyz="-1.5 0 0"
        rpy="0 0 -1.57079632679"/>
  </joint>

</robot>
