kr_50_r2500:
  foulder_path: '/home/gauss/projects/personal_ws/src/kr_50_r2500/kr_50_r2500_description/urdf'
  xacro_file_name: 'kr_50_r2500_pybullet'   # an urdf file with the same name will be generated
  controlled_joint_name: ['joint1', 'joint2', 'joint3', 'joint4', 'joint5', 'joint6']
  joint_control_mode : 'position' # position (which is in fact POSITION_VELOCITY_PD), velocity, torque and pd.
