$(arg robot_name):
  package_name: 'kr_50_r2500_description'
  xacro_file_path: 'urdf/kr_50_r2500_pybullet.xacro'   # an urdf file with the same name will be generated
  controlled_joint_name: ['$(arg prefix)joint1', '$(arg prefix)joint2', '$(arg prefix)joint3', '$(arg prefix)joint4', '$(arg prefix)joint5', '$(arg prefix)joint6']
  joint_control_mode : 'position' # position (which is in fact POSITION_VELOCITY_PD), velocity, torque and pd.
  sensors: # define an array that containing the sensorized joints
  - '$(arg prefix)link6_to_flange'
