controller_list:
  - name: fake_kr_50_r2500_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_visual_fingerA_joint_2
      - gripper_visual_fingerA_joint_3
      - gripper_visual_fingerA_joint_4
      - gripper_visual_fingerB_knuckle
      - gripper_visual_fingerB_joint_2
      - gripper_visual_fingerB_joint_3
      - gripper_visual_fingerB_joint_4
      - gripper_visual_fingerC_knuckle
      - gripper_visual_fingerC_joint_2
      - gripper_visual_fingerC_joint_3
      - gripper_visual_fingerC_joint_4
initial:  # Define initial robot poses per group
#  - group: kr_50_r2500
#    pose: home

  []